---
## Bootstrap the box on the AWS layer
- hosts: localhost
  vars_files:
    - my-vars.yml
  roles:
    - OULibraries.lastpass-cli
    - OULibraries.d7-lastpass
    - OULibraries.ec2-init
## Do provisioning inside the box
- hosts: unprovisioned
  remote_user: libacct
  sudo: yes
  roles:
    - OULibraries.centos7
    - OULibraries.d7
## Do post-provisioning tasks on the AWS layer
- hosts: localhost
  tasks:
    - name: Tag instance after provisioning
      ec2_tag:
        region: "{{ hostvars['localhost']['region'] }}"
        resource: "{{ hostvars['localhost']['instance_id'] }}"
        state: present
        tags:
          Workload: "{{ hostvars['localhost']['server_tag_workload'] }}"
