---
- src: https://github.com/OULibraries/ansible-role-ec2-init
  version: v2016-05-12.0
  name: OULibraries.ec2-init

- src: https://github.com/OULibraries/ansible-role-lastpass-cli
  version: v2016-04-08.0
  name: OULibraries.lastpass-cli

- src: https://github.com/OULibraries/ansible-role-d7-lastpass
  version: v2016-04-16.0
  name: OULibraries.d7-lastpass

- src: https://github.com/OULibraries/ansible-role-centos7
  version: v2016-05-03.0
  name: OULibraries.centos7
  
- src: https://github.com/OULibraries/ansible-role-users
  version: v2016-05-11.2
  name: OULibraries.users
  
- src: https://github.com/OULibraries/ansible-role-apache2
  version: v2016-04-25.1
  name: OULibraries.apache2
  
- src: https://github.com/OULibraries/ansible-role-mariadb
  version: v2016-04-08.0
  name: OULibraries.mariadb

- src: https://github.com/OULibraries/ansible-role-d7
  version: v2016-05-04.0
  name: OULibraries.d7
