---
# fetch OULibraries.lastpass-cli from github
- src: https://github.com/OULibraries/ansible-role-lastpass-cli
  version: master
  name: OULibraries.lastpass-cli
# fetch OULibraries.d7-lastpass from github
- src: https://github.com/OULibraries/ansible-role-d7-lastpass
  version: master
  name: OULibraries.d7-lastpass
# fetch OULibraries.ec2-init from github
- src: https://github.com/OULibraries/ansible-role-ec2-init
  version: v2016-04-08.0
  name: OULibraries.ec2-init
# fetch OULibraries.centos7 from github
- src: https://github.com/OULibraries/ansible-role-centos7
  version: master
  name: OULibraries.centos7
# fetch OULibraries.d7 from github
- src: https://github.com/OULibraries/ansible-role-d7
  version: v2016-04-06.0
  name: OULibraries.d7
